### PR TITLE
first go at using datatypes

### PR DESCRIPTION
**Pull request by jgrammen-agilitypr**
### Overview

Switch to using puppet 5 native datatypes, this should prevent deprecation warnings with stdlib as it removes the *_validate commands

### Related issues

#49

### CODE REVIEW

**Comment by Ma27** [comment]
seems fine, let's merge for now :)

**Comment by zebraf1** [comment]
I am also getting these deprecation warnings with the latest 1.2.7 release. When will this be released?
I upgraded from puppet 3 to 6 and this composer module works perfectly (except for the deprecation warning caused by newer stdlib 5.1.0)

**Comment by Ma27** [comment]
It's on my todo list, I need to find some time for this, but at least there are no blockers for the upcoming release :)

**Comment by zebraf1** [comment]
Thanks for you fast feedback! Keep up the good work

**Pull request merged**
